// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Plugin struct {
	ID                int64
	Name              string
	Slug              string
	Description       string
	Url               string
	OriginID          int64
	IsUpdatedOnServer int64
	CreatedAt         string
	UpdatedAt         string
}

type PluginChangelog struct {
	ID         int64
	PluginID   int64
	Version    string
	Changelog  string
	UpdateDate string
	CreatedAt  string
	UpdatedAt  string
}

type PluginCommand struct {
	ID          int64
	PluginID    int64
	Command     string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type PluginConfig struct {
	ID         int64
	PluginID   int64
	ConfigJson string
	CreatedAt  string
	UpdatedAt  string
}

type PluginDoc struct {
	ID        int64
	PluginID  int64
	Doc       string
	CreatedAt string
	UpdatedAt string
}

type PluginImage struct {
	ID        int64
	PluginID  int64
	Image     []byte
	CreatedAt string
	UpdatedAt string
}

type PluginLocale struct {
	PluginID    int64
	LangCode    string
	LangName    string
	ContentJson string
	CreatedAt   string
	UpdatedAt   string
}

type PluginManualCodeChange struct {
	ID           int64
	PluginID     int64
	ModifiedPart string
	RowStart     int64
	RowEnd       int64
	Comment      string
	IsRelevant   int64
	CreatedAt    string
	UpdatedAt    string
}

type PluginOrigin struct {
	ID               int64
	Name             string
	Slug             string
	Url              string
	PathToPluginList string
	HasApi           int64
	CreatedAt        string
	UpdatedAt        string
}
