// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_locales.sql

package database

import (
	"context"
)

const addPluginLocale = `-- name: AddPluginLocale :one
INSERT INTO plugin_locales(
    plugin_id, lang_code,
    lang_name, content_json,
    created_at, updated_at
)
SELECT p.id, ?, ?, ?, datetime('now'), datetime('now')
FROM plugins AS p
WHERE p.slug = ?
RETURNING plugin_id, lang_code, lang_name, content_json, created_at, updated_at
`

type AddPluginLocaleParams struct {
	LangCode    string
	LangName    string
	ContentJson string
	Slug        string
}

func (q *Queries) AddPluginLocale(ctx context.Context, arg AddPluginLocaleParams) (PluginLocale, error) {
	row := q.db.QueryRowContext(ctx, addPluginLocale,
		arg.LangCode,
		arg.LangName,
		arg.ContentJson,
		arg.Slug,
	)
	var i PluginLocale
	err := row.Scan(
		&i.PluginID,
		&i.LangCode,
		&i.LangName,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePluginLocale = `-- name: DeletePluginLocale :one
DELETE
FROM plugin_locales
WHERE lang_code = ? AND plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
RETURNING plugin_id, lang_code, lang_name, content_json, created_at, updated_at
`

type DeletePluginLocaleParams struct {
	LangCode string
	Slug     string
}

func (q *Queries) DeletePluginLocale(ctx context.Context, arg DeletePluginLocaleParams) (PluginLocale, error) {
	row := q.db.QueryRowContext(ctx, deletePluginLocale, arg.LangCode, arg.Slug)
	var i PluginLocale
	err := row.Scan(
		&i.PluginID,
		&i.LangCode,
		&i.LangName,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginLocale = `-- name: GetPluginLocale :one
SELECT plugin_id, lang_code, lang_name, content_json, created_at, updated_at
FROM plugin_locales
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
) AND lang_code = ?
`

type GetPluginLocaleParams struct {
	Slug     string
	LangCode string
}

func (q *Queries) GetPluginLocale(ctx context.Context, arg GetPluginLocaleParams) (PluginLocale, error) {
	row := q.db.QueryRowContext(ctx, getPluginLocale, arg.Slug, arg.LangCode)
	var i PluginLocale
	err := row.Scan(
		&i.PluginID,
		&i.LangCode,
		&i.LangName,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginLocales = `-- name: GetPluginLocales :many
SELECT plugin_id, lang_code, lang_name, content_json, created_at, updated_at
FROM plugin_locales
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
`

func (q *Queries) GetPluginLocales(ctx context.Context, slug string) ([]PluginLocale, error) {
	rows, err := q.db.QueryContext(ctx, getPluginLocales, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginLocale
	for rows.Next() {
		var i PluginLocale
		if err := rows.Scan(
			&i.PluginID,
			&i.LangCode,
			&i.LangName,
			&i.ContentJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePluginLocale = `-- name: UpdatePluginLocale :one
UPDATE plugin_locales
SET content_json = ?,
    updated_at = datetime('now')
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
) AND lang_code = ?
RETURNING plugin_id, lang_code, lang_name, content_json, created_at, updated_at
`

type UpdatePluginLocaleParams struct {
	ContentJson string
	Slug        string
	LangCode    string
}

func (q *Queries) UpdatePluginLocale(ctx context.Context, arg UpdatePluginLocaleParams) (PluginLocale, error) {
	row := q.db.QueryRowContext(ctx, updatePluginLocale, arg.ContentJson, arg.Slug, arg.LangCode)
	var i PluginLocale
	err := row.Scan(
		&i.PluginID,
		&i.LangCode,
		&i.LangName,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
