// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_configs.sql

package database

import (
	"context"
)

const addPluginConfig = `-- name: AddPluginConfig :one
INSERT INTO plugin_configs(plugin_id, config_json, created_at, updated_at)
SELECT p.id, ?, datetime('now'), datetime('now')
FROM plugins AS p
WHERE p.slug = ?
RETURNING id, plugin_id, config_json, created_at, updated_at
`

type AddPluginConfigParams struct {
	ConfigJson string
	Slug       string
}

func (q *Queries) AddPluginConfig(ctx context.Context, arg AddPluginConfigParams) (PluginConfig, error) {
	row := q.db.QueryRowContext(ctx, addPluginConfig, arg.ConfigJson, arg.Slug)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePluginConfig = `-- name: DeletePluginConfig :one
DELETE
FROM plugin_configs
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
RETURNING id, plugin_id, config_json, created_at, updated_at
`

func (q *Queries) DeletePluginConfig(ctx context.Context, slug string) (PluginConfig, error) {
	row := q.db.QueryRowContext(ctx, deletePluginConfig, slug)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginConfig = `-- name: GetPluginConfig :one
SELECT id, plugin_id, config_json, created_at, updated_at
FROM plugin_configs
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
`

func (q *Queries) GetPluginConfig(ctx context.Context, slug string) (PluginConfig, error) {
	row := q.db.QueryRowContext(ctx, getPluginConfig, slug)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePluginConfig = `-- name: UpdatePluginConfig :one
UPDATE plugin_configs
SET config_json = ?, updated_at = datetime('now')
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
RETURNING id, plugin_id, config_json, created_at, updated_at
`

type UpdatePluginConfigParams struct {
	ConfigJson string
	Slug       string
}

func (q *Queries) UpdatePluginConfig(ctx context.Context, arg UpdatePluginConfigParams) (PluginConfig, error) {
	row := q.db.QueryRowContext(ctx, updatePluginConfig, arg.ConfigJson, arg.Slug)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
