// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_docs.sql

package database

import (
	"context"
)

const addPluginDoc = `-- name: AddPluginDoc :one
INSERT INTO plugin_docs(plugin_id, doc, created_at, updated_at)
SELECT p.id, ?, datetime('now'), datetime('now')
FROM plugins AS p
WHERE p.slug = ?
RETURNING id, plugin_id, doc, created_at, updated_at
`

type AddPluginDocParams struct {
	Doc  string
	Slug string
}

func (q *Queries) AddPluginDoc(ctx context.Context, arg AddPluginDocParams) (PluginDoc, error) {
	row := q.db.QueryRowContext(ctx, addPluginDoc, arg.Doc, arg.Slug)
	var i PluginDoc
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Doc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePluginDoc = `-- name: DeletePluginDoc :one
DELETE
FROM plugin_docs
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
RETURNING id, plugin_id, doc, created_at, updated_at
`

func (q *Queries) DeletePluginDoc(ctx context.Context, slug string) (PluginDoc, error) {
	row := q.db.QueryRowContext(ctx, deletePluginDoc, slug)
	var i PluginDoc
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Doc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginDoc = `-- name: GetPluginDoc :one
SELECT id, plugin_id, doc, created_at, updated_at
FROM plugin_docs
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
`

func (q *Queries) GetPluginDoc(ctx context.Context, slug string) (PluginDoc, error) {
	row := q.db.QueryRowContext(ctx, getPluginDoc, slug)
	var i PluginDoc
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Doc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePluginDoc = `-- name: UpdatePluginDoc :one
UPDATE plugin_docs
SET doc = ?,
    updated_at = datetime('now')
WHERE plugin_id = (
    SELECT id
    FROM plugins
    WHERE slug = ?
)
RETURNING id, plugin_id, doc, created_at, updated_at
`

type UpdatePluginDocParams struct {
	Doc  string
	Slug string
}

func (q *Queries) UpdatePluginDoc(ctx context.Context, arg UpdatePluginDocParams) (PluginDoc, error) {
	row := q.db.QueryRowContext(ctx, updatePluginDoc, arg.Doc, arg.Slug)
	var i PluginDoc
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Doc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
